### ISSUE TITLE
Mod no longer works

### ISSUE THREAD

**Issue by harbingerofme** [DekuDesu/MiniMapMod#1]
This mod calls charactermaster.get_alive() which no longer exists in the ror2 assembly.
I have deprecated the mod on Thunderstore for now, but pushing an update will automatically undeprecate this.

**Comment by DekuDesu** [comment]
Fixed with 5fff3b8, ThunderIO release to be updated within the week with up-to-date README, manifest, and images.

**Comment by DekuDesu** [comment]
Final Release complete with a550f3e
