### ISSUE TITLE
Item Printers to use a different icon or color?

### ISSUE THREAD

**Issue by Bogdanov89** [DekuDesu/MiniMapMod#19]
Thank you for the amazing mod!
Would it please be possible for item printers to use a different icon (or color) on the minimap (currently they look identical like chests)?
Commonly the item printers are undesirable and seeing them as unopened chests on the minimap is often causing confusion.
Thank you again!

**Comment by DekuDesu** [comment]
Currently the icons load dynamically from what's available inside RoR2. I will take a look and see what I can come up with

**Comment by DekuDesu** [comment]
Approved and implemented, see [9abb69f](https://github.com/DekuDesu/MiniMapMod/commit/9abb69f1263e60046d628d9ade5d38bb33895b96)
