### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by KAKUJY07** [DekuDesu/MiniMapMod#20]
I love this mod.
But have a few small suggestions:
Can you add a configuration to customize the on/off of each icon? because I find that in multiplayer there are so many icons to display that they all overlap. Like enemies and drones, I don't think it's important.
The other one is printer icon is same as the chest icon, it is difficult to distinguish.
Finally, I hope to add Newt Altars icon.
My English is not good, so I used a translation tool.
Thanks again!

**Comment by DekuDesu** [comment]
> Can you add a configuration to customize the on/off of each icon? because I find that in multiplayer there are so many icons to display that they all overlap. Like enemies and drones, I don't think it's important.
Approved and implemented, see [9abb69f](https://github.com/DekuDesu/MiniMapMod/commit/9abb69f1263e60046d628d9ade5d38bb33895b96)

> Finally, I hope to add Newt Altars icon.
Request denied. The lack of newt altars is intentional.

Thank you for your suggestions.
