### ISSUE TITLE
MiniMapMod doesn't show Adaptive Chests

### ISSUE THREAD

**Issue by SennytheSnek** [DekuDesu/MiniMapMod#22]
![изображение_2022-03-13_202431](https://user-images.githubusercontent.com/101520146/158071402-f6ab0a93-ca64-46b3-b450-75d7042ee4e7.png)

**Comment by DekuDesu** [comment]
SHOULD be fixed with [2bac2fc](https://github.com/DekuDesu/MiniMapMod/commit/2bac2fc930863a21a3da03232b31e767845d62f4), however, I spent 4 hours trying to find one to confirm and couldn't find one. Let me know if it's not fixed
