### ISSUE TITLE
Explanations for some of the new sections in config.

### ISSUE THREAD

**Issue by Bogdanov89** [DekuDesu/MiniMapMod#23]
Thank you for the awesome update, its great being able to adjust icons!
If you can please elaborate what objects do following sections include:
-Icon.none
-Icon.Primary
-Icon.Special
-Icon.Utility

Your mod makes RoR2 so much more enjoyable to play :)

**Comment by Bogdanov89** [comment]
If you can please assist, I tried to edit the icon colors of the lunar pods and the void pods and the 3-item shops but could not find any category that affect them in the config page of the mod.

**Comment by DekuDesu** [comment]
Thanks for the feedback. I have added descriptions such as the following into the config to help:
```
Whether or All shrines (excluding Newt) should be shown on the minimap.
```

> Icon.none
Not used, removed from the config file

> Icon.Primary
Deprecated, removed from config file

> Icon.Utility
Scrappers

> Icon.Special
Things like the first landing pod that has a door on the back.

see [2bac2fc](https://github.com/DekuDesu/MiniMapMod/commit/2bac2fc930863a21a3da03232b31e767845d62f4)

**Comment by DekuDesu** [comment]
> If you can please assist, I tried to edit the icon colors of the lunar pods and the void pods and the 3-item shops but could not find any category that affect them in the config page of the mod.

Added separate lunar pod icon see [2bac2fc](https://github.com/DekuDesu/MiniMapMod/commit/2bac2fc930863a21a3da03232b31e767845d62f4)
