### ISSUE TITLE
Issues with payouts from teleporters and shrines.

### ISSUE THREAD

**Issue by Tumidiagram** [DekuDesu/MiniMapMod#31]
For some reason whenever the minimap mod is enabled there is an issue with bosses not giving a payout of items.

**Comment by DekuDesu** [comment]
I was not able to reproduce this issue over the course of 2 hours of play testing.

This mod performs `readonly` scans of the game and has no access to item pools or drops.

You may want to consider looking into other mods that may be causing this behavior or may be conflicting with the minimap mod in some way.
