### ISSUE TITLE
invisible chests

### ISSUE THREAD

**Issue by Petriell0** [DekuDesu/MiniMapMod#32]
Invisible chests appear on the minimap breaking the idea of ​​finding them,

**Comment by DekuDesu** [comment]
fixed, see [590ca86](https://github.com/DekuDesu/MiniMapMod/commit/590ca86b5846b11d43fdeafb75152c3e3b6212a0)

**Comment by aaomidi** [comment]
Do you think it would be okay to have this configurable (default turned off) for users?
