### ISSUE TITLE
Newt Altars (Blue Portals)

### ISSUE THREAD

**Issue by Petriell0** [DekuDesu/MiniMapMod#33]
Newt Altars (Blue Portals) are not shown on the map.

**Comment by DekuDesu** [comment]
Thank you for your suggestion.

Newt altars, invisible chests, and timed chests are intentionally excluded from the minimap for balance purposes.

There is no plan on adding this feature, however, this may change in the future.

**Comment by Petriell0** [comment]
> Thank you for your suggestion.
> 
> Newt altars, invisible chests, and timed chests are intentionally excluded from the minimap for balance purposes.
> 
> There is no plan on adding this feature, however, this may change in the future.

I understand that you do this and possibly this project for free, as others I said it's always good to have, no matter how long it takes to be added, I know what it's like to work with accredited codes, I have a project that I work on a website that I've worked on for 5 years , in order not to be released and delayed.

and I've been working with the unit for months, making my own game.

I know how tiring it is to test every code update, seeing if it's correct.

in the last few months I wrote a massive procedural generation and data compression with 130+GB to 1XXMBs

a total of 2000 lines, and still not close to the end.

My last comment, rest your head a little.

**Comment by DekuDesu** [comment]
Thank you again for your suggestion.

I am currently working on several critical compatibility issues for this repo.

I will *consider* adding a **disabled by default** toggle for this feature. 

There is no time frame available for this feature, and is not guaranteed to be implemented.

Thanks again.
