### ISSUE TITLE
golden printers

### ISSUE THREAD

**Issue by Petriell0** [DekuDesu/MiniMapMod#34]
changing the color of the printer icons only affects the default printers, golden printers remain with the default color

**Comment by DekuDesu** [comment]
I was not able to find any golden printers in any run to grab the information required to implement this feature.

If you come across another golden printer and you have the mod *UnityExplorer* installed please obtain the purchase interaction context token.

This can be found by locating the printer object, clicking on the `PurchaseInteraction` component, and scrolling until you see `PurchaseInteraction.contextToken`.

It should look something like "GOLD_DUPLICATOR_CONTEXT".

Thanks

**Comment by Petriell0** [comment]
> I was not able to find any golden printers in any run to grab the information required to implement this feature.
> 
> If you come across another golden printer and you have the mod _UnityExplorer_ installed please obtain the purchase interaction context token.
> 
> This can be found by locating the printer object, clicking on the `PurchaseInteraction` component, and scrolling until you see `PurchaseInteraction.contextToken`.
> 
> It should look something like "GOLD_DUPLICATOR_CONTEXT".
> 
> Thanks

I'm not going to someone's work, imagine the risk of rain 2 asking you to help fix a bug you reported was caused by them.

another thing is that, leaving invisible chests visible and stores invisible on the map is not balancing, and even if you are a developer / programmer, you have to leave options for your customers / players, each player has a taste and a way of playing , it's not just that you say it's good for you, it's great for everyone.

I'm a programmer and I understand each of the challenges of creating a mod, but this is one thing if your mod SHOULD HAVE, as optional always.

imagine a mod that you remove elite enemies, only it includes the special bosses as elite, if the player wants to change because he thought he didn't remove the special bosses, he MUST have an option to rehabilitate, and customize his game as he wants.

**Comment by DekuDesu** [comment]
I do this for free bud. Closed.

**Comment by DekuDesu** [comment]
Fixed see 65b16fe
