### ISSUE TITLE
After the update, this mod started conflicting with MysticsItems by TheMysticSword, which causes these issues:

### ISSUE THREAD

**Issue by SennytheSnek** [DekuDesu/MiniMapMod#37]
1. The Minimap itself is completely broken and shows nothing but a white circle with a transparent background
2. No items drop from Sacrifice or Teleporter boss rewards
3. Railgunner's piercing (long-range secondary and specials) breaks entirely
These are all the bugs that I know of so far.
Please fix if possible.
I have also notified TheMysticSword on the Risk of Rain 2 Modding discord

**Comment by DekuDesu** [comment]
Confirmed compatibility issue. Working on patch now.

**Comment by DekuDesu** [comment]
fixed with [677270f](https://github.com/DekuDesu/MiniMapMod/commit/677270f0f6b48d163e34a9851d0f6d91f5f693dc)
