### ISSUE TITLE
Multishop terminals & equipment chests to be a different color than regular chests?

### ISSUE THREAD

**Issue by Bogdanov89** [DekuDesu/MiniMapMod#42]
Thanks for this awesome mod!

With the new possible equipment item "Executive Card" (allows purchasing of all 3 items from all Multishop terminals) the players are actually encouraged to first loot all the chests and anything that can drop the "Executive Card" before actually going to use Multishop terminals, due to the huge power difference it gives by letting players buy all three items instead of just one.

Would it please be possible to make Multishop terminals a separate config section so that they can be differently colored than regular chests?
The same separate option would be great for "equipment chests" and "equipment multishop terminals" so that when we already have the ideal equipment item we can ignore the other equipment chests, instead of visiting them only to then see it is not a regular chest.
Thanks!

**Comment by DekuDesu** [comment]
> Would it please be possible to make Multishop terminals a separate config section so that they can be differently colored than regular chests?

> The same separate option would be great for "equipment chests" and "equipment multishop terminals" so that when we already have the ideal equipment item we can ignore the other equipment chests, instead of visiting them only to then see it is not a regular chest.

Yes, both of these are planned to be release in v3.2. If you would like to test those features before they are released on the thunderstore you can download the experimental build  [over here](https://github.com/DekuDesu/MiniMapMod/releases/tag/experimental_3.2.0).

**Comment by DekuDesu** [comment]
Released in stable 3.2.0 see #46
