### ISSUE TITLE
Custom minimap zoom

### ISSUE THREAD

**Issue by MightyW0lf** [DekuDesu/MiniMapMod#49]
Either as a keybind (Numpad +/-?) or configurable. Currently I think the minimap is a bit too zoomed out, but that's a personal preference I guess.

**Comment by DekuDesu** [comment]
I can take a look for you. No promises. :3

**Comment by DekuDesu** [comment]
Implemented in 3.3.1, see experimental build [3.3.1](https://github.com/DekuDesu/MiniMapMod/releases/tag/experimental_3.3.1). Will be released on thunderio with next stable version.

![image](https://user-images.githubusercontent.com/39616108/159158482-96649c9c-f0ba-45f5-a9e7-8ea44fe2688c.png)
