### ISSUE TITLE
Icons cannot be closed correctly.

### ISSUE THREAD

**Issue by Fiocher** [DekuDesu/MiniMapMod#53]
I turned off Barrel, Drone, Enemy, Equipment, Landing Pod in the config, but they still showed up on the minimap. Other icons are not tested and may all can not be closed.
![Snipaste_2022-03-21_10-15-30](https://user-images.githubusercontent.com/82749343/159197982-374d6538-8c3b-45da-93ed-b94f47abc2ae.png)

**Comment by DekuDesu** [comment]
fixed with [df87745](https://github.com/DekuDesu/MiniMapMod/commit/df8774557c9b1d552488777cd562ba01e451f99d). Latest binaries available via Releases on github. Thunderio hotfix will be released momentarily.
